github actions: take improvements from panicparse/gh

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -14,7 +14,12 @@
 on: [push, pull_request]
 name: Run tests
 jobs:
-  test_all:
+    # Runs go test both with code coverage sent to codecov, race detector and
+    # benchmarks. At the end do a quick check to ensure the tests to not leave
+    # files in the tree.
+  test:
+    name: "test: go${{matrix.gover}}.x/${{matrix.os}}"
+    runs-on: "${{matrix.os}}"
     continue-on-error: true
     defaults:
       run:
@@ -24,20 +29,85 @@ jobs:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         # Do not forget to bump every 6 months!
-        gover: ["1.17"]
-    runs-on: "${{matrix.os}}"
-    name: "go${{matrix.gover}}.x on ${{matrix.os}}"
+        gover: ["1.18"]
     env:
       PYTHONDONTWRITEBYTECODE: x
     steps:
-    - uses: actions/setup-go@v2
-      with:
-        go-version: "${{matrix.gover}}"
-
-      # Checkout and print debugging information.
     - name: Turn off git core.autocrlf
+      if: matrix.os == 'windows-latest'
       run: git config --global core.autocrlf false
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 2
+    - uses: actions/setup-go@v3
+      with:
+        go-version: "~${{matrix.gover}}.0"
+        cache: true
+    - name: 'go install necessary tools'
+      if: always()
+      run: |
+        go install github.com/maruel/pat/cmd/ba@latest
+    - name: 'Check: go test -cover'
+      if: always()
+      run: go test -timeout=120s -covermode=count -coverprofile coverage.txt ./...
+      # Don't send code coverage if anything failed to reduce spam.
+    - uses: codecov/codecov-action@v2
+    - name: 'Cleanup'
+      if: always()
+      run: rm coverage.txt
+    - name: 'Check: go test -race'
+      run: go test -timeout=60s -race ./...
+    - name: 'Check: go test -bench=.'
+      run: go test -timeout=60s -bench=. -benchtime=100ms -cpu=1  -run NONE ./...
+    - name: 'Check: go test (32 bits, short)'
+      if: matrix.os != 'macos-latest'
+      env:
+        GOARCH: 386
+      run: go test -timeout=40s -short ./...
+    - name: "Check: tree is clean"
+      if: always()
+      run: |
+        # Nothing should have changed in the tree up to that point and no
+        # unsuspected file was created.
+        TOUCHED=$(git status --porcelain --ignored)
+        if ! test -z "$TOUCHED"; then
+          echo "Oops, something touched these files, please cleanup:"
+          echo "$TOUCHED"
+          git diff
+          false
+        fi
+
+
+    # Run linters. This workflow can be merged with the test_all one if desired
+    # to cut on runtime, at the cost of latency. I dislike waiting for results
+    # so I prefer to run them in parallel.
+  lint:
+    name: "lint: go${{matrix.gover}}.x/${{matrix.os}}"
+    runs-on: "${{matrix.os}}"
+    continue-on-error: true
+    defaults:
+      run:
+        shell: bash
+    strategy:
+      fail-fast: false
+      matrix:
+        # You may want to run only on linux to save on cost. Projects with
+        # OS-specific code benefits from explicitly linting on macOS and
+        # Windows.
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        # Do not forget to bump every 6 months!
+        gover: ["1.18"]
+    env:
+      PYTHONDONTWRITEBYTECODE: x
+    steps:
+    - name: Turn off git core.autocrlf
+      if: matrix.os == 'windows-latest'
+      run: git config --global core.autocrlf false
+    - uses: actions/checkout@v3
+    - uses: actions/setup-go@v3
+      with:
+        go-version: "~${{matrix.gover}}.0"
+        cache: true
     - name: "Debug"
       run: |
         echo HOME = $HOME
@@ -46,101 +116,37 @@ jobs:
         echo ""
         echo $ ls -l $HOME/go/bin
         ls -la $HOME/go/bin
-
-    - name: 'Cache: ~/go'
-      uses: actions/cache@v2
-      with:
-        path: ~/go
-        key: "${{runner.os}}-gopkg-${{hashFiles('go.sum', '.github/workflows/*.yml')}}"
-
-      # Run tests first because it's important.
-    - name: 'Check: go test -cover'
-      run: go test -timeout=120s -covermode=count -coverprofile coverage.txt ./...
-    - uses: codecov/codecov-action@v2
-    - name: 'Cleanup'
-      if: always()
-      run: rm coverage.txt
-
-      # Don't run go test -race if anything failed, to speed up the results.
-    - name: 'Check: go test -race'
-      run: go test -timeout=120s -race ./...
-    - name: 'Check: go test -bench=.'
-      run: go test -timeout=120s -bench=. -benchtime=100ms -cpu=1  -run NONE ./...
-
-    - name: "Check: tree is clean"
-      if: always()
-      run: |
-        # Nothing should have changed in the tree up to that point and no
-        # unsuspected file was created.
-        TOUCHED=$(git status --porcelain)
-        if ! test -z "$TOUCHED"; then
-          echo "Oops, something touched these files, please cleanup:"
-          echo "$TOUCHED"
-          git diff
-          false
-        fi
-
-    - name: "Check: go generate doesn't modify files"
-      if: always()
-      run: |
-        go generate ./...
-        # Also test for untracked files.
-        TOUCHED=$(git status --porcelain)
-        if ! test -z "$TOUCHED"; then
-          echo "go generate created these files, please fix:"
-          echo "$TOUCHED"
-          false
-        fi
-
-    - name: "Check: go mod tidy doesn't modify files"
-      if: always()
-      run: |
-        go mod tidy
-        TOUCHED=$(git status --porcelain)
-        if ! test -z "$TOUCHED"; then
-          echo "go mod tidy was not clean, please update:"
-          git diff
-          false
-        fi
-
-      # Fetch the tools.
-    - name: 'go get necessary tools'
+    - name: 'go install necessary tools'
       if: always()
       run: |
         go install github.com/gordonklaus/ineffassign@latest
-        go install github.com/securego/gosec/cmd/gosec@latest
-        go install golang.org/x/lint/golint@latest
+        go install github.com/securego/gosec/v2/cmd/gosec@latest
         go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
         go install honnef.co/go/tools/cmd/staticcheck@latest
-    - name: 'go get necessary tools (ubuntu)'
+    - name: 'go install necessary tools (ubuntu)'
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
         go install github.com/client9/misspell/cmd/misspell@latest
         go install github.com/google/addlicense@latest
-
-      # Now run proper checks.
     - name: 'Check: go vet'
       if: always()
       run: go vet ./...
     - name: 'Check: go vet shadow; shadowed variables'
+      if: always()
       run: |
         SHADOW_TOOL="$(which shadow)"
         if [ -f "${SHADOW_TOOL}.exe" ]; then
           SHADOW_TOOL="${SHADOW_TOOL}.exe"
         fi
         go vet -vettool=$SHADOW_TOOL ./...
-    - name: 'Check: golint'
-      if: always()
-      run: golint -set_exit_status ./...
     - name: 'Check: inefficient variable assignment'
       if: always()
       run: ineffassign ./...
     - name: 'Check: staticcheck'
       if: always()
       run: staticcheck ./...
-    - name: 'Check: gosec (only G104)'
-      run: gosec -include=G104 -fmt=golint -quiet ./...
-
+    - name: 'Check: gosec'
+      run: gosec -exclude=G204,G304 -fmt=golint -quiet ./...
       # The following checks are not dependent on the OS or go build tags. Only
       # run them on ubuntu-latest since it's the fastest one.
     - name: 'Check: no executable was committed (ubuntu)'
@@ -150,6 +156,9 @@ jobs:
           echo 'Do not commit executables beside shell scripts'
           false
         fi
+    - name: 'Check: addlicense; all sources have a license header (ubuntu)'
+      if: always() && matrix.os == 'ubuntu-latest'
+      run: addlicense -check .
     - name: 'Check: gofmt; code is well formatted (ubuntu)'
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
@@ -167,9 +176,6 @@ jobs:
           echo "" >> _comments.txt
           false
         fi
-    - name: 'Check: addlicense; all sources have a license header (ubuntu)'
-      if: always() && matrix.os == 'ubuntu-latest'
-      run: addlicense -check .
     - name: "Check: misspelling; code doesn't contain misspelling (ubuntu)"
       if: always() && matrix.os == 'ubuntu-latest'
       run: |
@@ -182,7 +188,6 @@ jobs:
           echo "" >> _comments.txt
           false
         fi
-
     - name: 'Send comments'
       if: failure() && github.event_name == 'pull_request'
       run: |
@@ -194,23 +199,55 @@ jobs:
             --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
             --header "Content-Type: application/json" \
             --data "${PAYLOAD}" "${URL}" > /dev/null
+          rm _comments.txt
+        fi
+    - name: "Check: go generate doesn't modify files"
+      if: always()
+      run: |
+        go generate ./...
+        # Also test for untracked files. go generate should not generate ignored
+        # files either.
+        TOUCHED=$(git status --porcelain --ignored)
+        if ! test -z "$TOUCHED"; then
+          echo "go generate created these files, please fix:"
+          echo "$TOUCHED"
+          false
+        fi
+    - name: "Check: go mod tidy doesn't modify files"
+      if: always()
+      run: |
+        go mod tidy
+        TOUCHED=$(git status --porcelain --ignored)
+        if ! test -z "$TOUCHED"; then
+          echo "go mod tidy was not clean, please update:"
+          git diff
+          false
         fi
 
-  test_32bits:
-    env:
-      GOARCH: 386
+
+  codeql:
+    name: "codeql: go${{matrix.gover}}.x/${{matrix.os}}"
+    runs-on: "${{matrix.os}}"
     continue-on-error: true
     strategy:
       fail-fast: false
       matrix:
+        os: [ubuntu-latest]
         # Do not forget to bump every 6 months!
-        gover: ["1.17"]
-    runs-on: ubuntu-latest
-    name: "go${{matrix.gover}}.x on ubuntu-latest 32 bits (quick)"
+        gover: ["1.18"]
+    permissions:
+      security-events: write
     steps:
-    - uses: actions/setup-go@v2
+    - uses: actions/checkout@v3
+    - uses: actions/setup-go@v3
       with:
-        go-version: "${{matrix.gover}}"
-    - uses: actions/checkout@v2
-    - name: 'Check: go test'
-      run: go test -timeout=40s ./...
+        go-version: "~${{matrix.gover}}.0"
+        cache: true
+    - name: Initialize CodeQL
+      uses: github/codeql-action/init@v2
+      with:
+        languages: go
+    - name: Autobuild
+      uses: github/codeql-action/autobuild@v2
+    - name: Perform CodeQL Analysis
+      uses: github/codeql-action/analyze@v2
